language: python
python:
- '2.7'
install:
- pip install pandas
script:
- pytest
deploy:
  provider: pypi
  user: malandru
  password:
    secure: g+Yketpjo7i2ewadxdfDvCPPF3Sx5LbLYf+UUQACf0GOYm3oFiwKHd2pphMRdBYtMq9W4NUsmDbPQEeFvCfeMM7iGPnPvFQHrWqUdNGsn1thQwfhGIWVqJC3GA9u1kdRJDqe1EqOXe+5pkGen/tonKfjo0qGfM2F00y+Z4L8u1CgjmFBf60jwLCab9kZ+xXhkqmIB9N/FT1Zm+cCaoIxrQEIIhHz06ar7IvJe8Aux1P24dRv2ypi7F6D909xLMjFAe8oiCzAbaD6/eIERPbUbEDLjxu37ShqXgoJaiPLq+xfWTzczZ57gdxli/5eXiASEmQSxKygeGWPs7qHn0VsHIyPqu+FZH059QhSFaTm05lRmaU5+kmQS/Se5no91hivRCyrWD5wMOhXdhQENayqyg+14W06hx85/TNmCUJ5/O6xkdPoPsqM3RCDT7+HUq5vXV/2+kdmhcclBQMZcencN6aq/CMaX9Urvl+bdlDmqSF3978UhNMr7+vNAdl4qvQltNXpBV0s/Cd3LDqerULLBvaZIp70Pg/Wxgp1qNJKViIWzcXCYlzeruYSO5rRfx25blxERLGJR6Nc7jpBbPzPNBGfgB8o7KwLG+qiBZsj3Y5ScQDUcV0e+ORUeQ374GqXd8Fqy0EIVwv0Ut4yFv33lmvgwk21/YtP1wydInfJd3k=
