language: python
python:
- '2.7'
install:
- pip install pandas
script:
- pytest
deploy:
  provider: pypi
  user: malandru
  password:
    secure: Gq24/K6wvrLhKH+jbhCVYfBjmdquf96sA9UQCzNRSXWlWvFafDjjBCioQ2VC+CVtZcrqg1HatIF7z8/KD2YmYiyG8V/YWuBD+fX5OaV/asgUfg/Lk9A+zUeDGm8HbjfDQePRY6DJmwxoAv1BHoKjCV2p4QLWfmvGIl+WO7fL8fotyX1QqOfsNW+I+RLVk4CPZ6Far5hkNH/bcxnXK61VJErfQM4APqGsZJgN7Y0f2Mi590i01K6bIvu0/c5JJ3DcTwWzPbC3Ve7Grsy2C9HXADQlYl8+BT7qpzl+asaNtUmg68dK/0wQbh96rbs9Vmkd2YQshnomL9NxiL1OeIKPVAG1Qya4elXlnGFMvpYHqDurIxBqFnV29cdmS7opU8bT/OqgCNDgEZ/YvKzLrmZXK0uLc6+32SOJhu1mkGyZDCBJxPENrtHp/RTuVgSZqvOOea+yYL0ys8/DgEn7U+rSfZznVoGd0KrBHPFxIFH1f47VHZLhi1ln2zzrXkqbj9sfNnn6Birpn+D4xj7yAje3fu+RlNijNZgiE+Bb6DEiGwSdUmrPOkg2UzafL7oPI9Ei2MLPWuY5LamgaXWsHT1EmgRn2fmCJofYv8LqpAfBJSS7hJfkLSOkrhg6W5jPnW7AbORAP2BoxST/DL4gAGlvhWHYbHVXmbyWgmcPNAXJPg8=
