language: python
python:
- '2.7'
install:
- pip install pandas
script:
- pytest
deploy:
  provider: pypi
  user: malandru
  password:
    secure: EKO1rrL91eFSo7pKgQvmiKoLUvV6t2D0Hab2T2nFM0Aiw4zlgz4560H1LAtIkd4D4P6oo1qu03aQHs6JfSS1m/0n9EXxZChxwQvSoMtBoFpk80KpFowUl0PpjoBhDjnxeuI39ks0nvzlt7AcdCQPYEPjp+fl+V14AWqSs1cUtugImo3q3QWIbeJ3W4rNaIZBEWdR6eEXWtiJbIvajFDlk4bpq18vjIiWuERm9QYGe8T8YikU+NwFmsWCmbHmzjubAPOHZCDEkhJPp7HVjT3aDZep46v71SllPt2XjnV6SqWVLfzw+0GnPxXUt4rutDzKp6wkkyLNtKP9PY2xaDcBV7k3s9oZtns8RZMz7nBXaAzvDwKedvT9OxSP7Ld+w210vOyl+VHiPsdiOhtfE7LsCW0ymbH63Ezq1YA2NxDDRs0ecfNLrWk3VaeqjgLtkpsY40T4jw4A+U+cjGpD0/fXw98eUEgThPxi7V5yi0e2bQnSuHmgzjiukmvKrqgB5ySfbZ2KAL3MbW8TuwYhmiI6AtuxWhuff5qgANmertV/q5bZ6tjUvRJzU0oEI3s8ZmuqE5Mw+lB5pS99JGuK1YZ1btqkMItR8iu8nzasg0mXsNdq5SHzu8ov2JysgCs0hMnAXBi4W8q0EzJLovI79H4t0zXBnnNvTx75PbXfPzE+eRU=
